"""Generate a ZGIIS TEC PDF report using fpdf2."""
from __future__ import annotations

import io
import datetime
from typing import Optional
import pandas as pd


def _format_table(pdf, df: pd.DataFrame, max_rows: int = 40) -> None:
    from fpdf import FPDF
    col_w = pdf.epw / len(df.columns)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(220, 230, 240)
    for col in df.columns:
        pdf.cell(col_w, 6, str(col)[:20], border=1, fill=True, align="C")
    pdf.ln()
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(20, 20, 20)
    for i, row in df.head(max_rows).iterrows():
        fill = (i % 2 == 0)
        pdf.set_fill_color(240, 248, 255) if fill else pdf.set_fill_color(255, 255, 255)
        for val in row:
            text = f"{val:.3f}" if isinstance(val, float) else str(val)[:20]
            pdf.cell(col_w, 5, text, border=1, fill=True, align="C")
        pdf.ln()


def generate_report(
    station: str,
    period: str,
    daily_df: Optional[pd.DataFrame],
    monthly_df: Optional[pd.DataFrame],
    sw_info: Optional[dict],
) -> bytes:
    """Return PDF bytes for a ZGIIS TEC report."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_fill_color(6, 13, 26)
    pdf.set_text_color(0, 212, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "ZGIIS — TEC Analysis Report", ln=True, align="C", fill=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 150, 200)
    pdf.cell(0, 6, "Zimbabwe GNSS Ionosphere Intelligence System", ln=True, align="C")
    pdf.cell(0, 5, "Monitoring the Invisible Space Environment Above Africa", ln=True, align="C")
    pdf.ln(4)

    # Metadata
    pdf.set_text_color(30, 30, 30)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, f"Station: {station.upper()}     Period: {period}", ln=True)
    pdf.cell(0, 6, f"Generated: {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", ln=True)
    pdf.ln(3)

    # Space weather
    if sw_info:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Space Weather Conditions", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"  Kp index: {sw_info.get('kp', 'N/A')}   Condition: {sw_info.get('kp_condition', 'N/A')}", ln=True)
        pdf.cell(0, 5, f"  F10.7: {sw_info.get('f107', 'N/A')} sfu   GNSS Risk: {sw_info.get('gnss_risk', 'N/A')}", ln=True)
        pdf.ln(3)

    # Daily table
    if daily_df is not None and not daily_df.empty:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Daily TEC Summary", ln=True)
        _format_table(pdf, daily_df)
        pdf.ln(4)

    # Monthly table
    if monthly_df is not None and not monthly_df.empty:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Monthly TEC Summary", ln=True)
        _format_table(pdf, monthly_df)

    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, "Generated by ZGIIS — Zimbabwe GNSS Ionosphere Intelligence System", ln=True, align="C")

    return pdf.output()
